title: "Disciplinas - Matemática"
description: "Cálculo | Vetores e Geometria Analítica | Geometria Euclidiana | Instituto Metrópole Digital (IMD) | Universidade Federal do Rio Grande do Norte (UFRN)"
theme: jekyll-theme-cayman
