title: "Disciplinas - Matemática"
description: "Cálculo | Geometria Analítica e Vetores | Instituto Metrópole Digital (IMD) | Universidade Federal do Rio Grande do Norte (UFRN)"
theme: jekyll-theme-cayman
